# Generated by Django 5.2 on 2025-04-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAula', '0004_post_imagem_post_subtitulo_alter_post_conteudo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.DeleteModel(
            name='Estudante',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
